name: uzum cicd example

on:
  push:
    branches: ['cicdtest','master','develop']

jobs:
  prep:
    name: clean and install application
    runs-on: ubuntu-latest
    steps:
      - name: checkou
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: clean
        run: mvn clean
      - name: test
        run: mvn test
      - name: install
        run: mvn install -DskipTests
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: docker/setup-buildx-action@v3.6.1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: iggytoto
          password: dckr_pat_Pdq4z27M9oLmwZhb-nG3-DgJD8M
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: iggytoto/uzum-test:latest
